language: haskell
ghc:
- 7.4
- 7.6
- 7.8
env:
  global:
    secure: KyAZkP0Gxv1yMtZNCmBns8guojQ99GCUSzbu4SNKxqPp6S0GXBrfqmXE98Myk8L/Yz+Xu9Z6qZy1xfMtSLjlakRuRNlWhzkShItqqD1MDTdrxNqfwxVJcQVv3SIPTws5suAG03yb5xYcKtlJ/L1NrQjIwiDlVnPr+I5SKGP/Krc=
